version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mssc-beer-service-data:/var/lib/mysql
    mem_limit: 512m

volumes:
  mssc-beer-service-data: